In [39]:
import pandas as pd
data = pd.read_csv('ex1data1.txt', header = None, names = ['Population','Profit'])
data.head()

Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [40]:
# Adding intercept term in our dataset
# using insert ny index = 0 (First column); header = Ones; values_to_insert = 1
data.insert(0,'Ones', 1)

In [41]:
data.head()

Ones  Population   Profit
0     1      6.1101  17.5920
1     1      5.5277   9.1302
2     1      8.5186  13.6620
3     1      7.0032  11.8540
4     1      5.8598   6.8233

In [42]:
# Seperating our training data(X) and target variable(y)
X = data.iloc[:,0:2]
y = data.iloc[:,2:]

In [43]:
print(X.shape)
print(y.shape)

(97, 2)
(97, 1)


In [44]:
# Initializing parameter vector theta
import numpy as np
theta = np.zeros((2,1))
print(theta)

theta.shape

[[0.]
 [0.]]


(2, 1)

#### Dataframe.values --> returns a numpy representation of the dataframe 
### Only the values in the DataFrame will be returned, the axes labels will be removed.


In [45]:
X = X.values
y = y.values
X.shape

(97, 2)

In [86]:
m = len(X)
# Our cost function
def compute_cost(X,y,theta):
    h = np.dot(X, theta) # (97,1)
    error = np.power((h - y), 2)
    J = (1/(2*m)) * np.sum(error)
    return J

In [47]:
Cost = compute_cost(X,y,theta)
print('Cost = ' + str(Cost))

Cost = 32.072733877455676


In [87]:
# Gradient Descent
m = len(X)
def Grad_descent(X, y, theta, alpha, iters):
    
    J_history = np.zeros((iters,1))
    
    for i in range(iters):
            h = np.dot(X, theta)
            error = h - y
            delta = np.dot(X.T, error)
            theta = theta - ((alpha / m) * delta)
            
            # Save the cost J in every iteration
            J_history[i] = compute_cost(X,y,theta)
            
    return theta, J_history


In [49]:
# Initialize variables for learning rate and iterations
theta = np.zeros((2,1))
alpha = 0.01
iters = 1500


theta, J_history = Grad_descent(X, y, theta, alpha, iters)
print('theta = ' + str(theta))


theta = [[-3.63029144]
 [ 1.16636235]]


In [50]:
# The theta vector describes the optimal linear model foe our datset. Let's check our cost/error to check how good our
# evaluation model is
compute_cost(X,y,theta)

4.483388256587725

That's a lot better than 32. But it's not a intuitive way to look at it.

In [129]:
# Predict Profit for the cityu with populkation of 35,000 and 7,000
# h = X * theta
profit1 = np.dot([1, 3.5], theta) * 10000
profit2 = np.dot([1, 7], theta) * 10000

print(profit1)
print(profit2)

[4519.7678677]
[45342.45012945]


### PART - 2  (Multivariate Linear Regression)
#### Predict the price that a house will sell for where this time we have multiple dependent variables or features 

In [111]:
data2 = pd.read_csv('ex1data2.txt', header = None, names = ['Size', 'Bedrooms', 'Price'])
data2.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

Notice that the scale of features/ variables is very different. If we run linewr regression as such, the 'size' variable would
be weighted too heavily and would end up dwarfing the 'bedrooms' varible. We need to do feature scaling in order to make features of similar scale.

By Substracting each value in a festure by mean of that feature, and the dividing by standard deviation. 

In [112]:
data2 = (data2 - data2.mean()) / data2.std()

In [113]:
# Adding a column of 1's ie; bias term in this dataset
data2.insert(0, 'Ones', 1)

In [114]:
data2.head()

Ones      Size  Bedrooms     Price
0     1  0.130010 -0.223675  0.475747
1     1 -0.504190 -0.223675 -0.084074
2     1  0.502476 -0.223675  0.228626
3     1 -0.735723 -1.537767 -0.867025
4     1  1.257476  1.090417  1.595389

In [115]:
# Selecting X and y
X2 = data2.iloc[:, 0:3]
y2 = data2.iloc[:,3:]

In [116]:
print(X2.shape)
print(y2.shape)

(47, 3)
(47, 1)


In [117]:
# Removing axes labels or converting dataframe X and y to numpy arrays
X2 = X2.values
y2 = y2.values

print(X2.shape)
print(y2.shape)

(47, 3)
(47, 1)


Now applying our algorithm, we dont need to change the algorithm as we did vectorized computation

In [125]:
# Initializing theta vector and other 2 parameters
theta2 = np.zeros((3,1))
iters = 1000

# Performing linear regresssion on the dataset
g2, cost2 = Grad_descent(X2, y2, theta2, alpha, iters)
print(g2)
print(cost2)

# Get the cost (error) of the model
compute_cost(X2,y2,g2)

[[-1.19343252e-16]
 [ 8.26450444e-01]
 [ 4.64110444e-03]]
[[0.23503676]
 [0.23298871]
 [0.23096884]
 [0.22897673]
 [0.227012  ]
 [0.22507423]
 [0.22316305]
 [0.22127807]
 [0.21941891]
 [0.21758519]
 [0.21577657]
 [0.21399266]
 [0.21223311]
 [0.21049758]
 [0.20878572]
 [0.20709718]
 [0.20543163]
 [0.20378875]
 [0.20216819]
 [0.20056965]
 [0.19899281]
 [0.19743734]
 [0.19590296]
 [0.19438934]
 [0.1928962 ]
 [0.19142324]
 [0.18997017]
 [0.18853671]
 [0.18712257]
 [0.18572747]
 [0.18435115]
 [0.18299333]
 [0.18165375]
 [0.18033215]
 [0.17902827]
 [0.17774185]
 [0.17647265]
 [0.17522041]
 [0.1739849 ]
 [0.17276588]
 [0.17156311]
 [0.17037636]
 [0.16920539]
 [0.16804999]
 [0.16690994]
 [0.165785  ]
 [0.16467497]
 [0.16357963]
 [0.16249878]
 [0.16143221]
 [0.16037971]
 [0.15934108]
 [0.15831613]
 [0.15730466]
 [0.15630647]
 [0.15532139]
 [0.15434922]
 [0.15338978]
 [0.15244289]
 [0.15150837]
 [0.15058605]
 [0.14967574]
 [0.14877729]
 [0.14789052]
 [0.14701527]
 [0.14615137]
 [0.14529866]
 [0.

0.06402598515964454

Looks promising ie; 0.06 error and we can see that error/cost is decreasing with each iteration of gradient descent.

### Lets implement our algorithm's using scikit - learns Linear Regression module 

In [128]:
from sklearn import linear_model
model = linear_model.LinearRegression()
model.fit(X2,y2)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)